In [1]:
import pandas as pd
import math
import numpy as np
import statistics
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy import stats
import researchpy as rp
import matplotlib.pyplot as plt


# Import the data from the spreadsheet
neutral_df = pd.read_excel('./neutral_com.xlsx')
neutral_df["Type"] = "Neutral"

inflam_df = pd.read_excel('./inflam_com.xlsx')
inflam_df["Type"] = "Inflam"

df = pd.concat([neutral_df, inflam_df])

In [2]:
# Two way ANOVA used for analysis of conversation data
# https://www.statology.org/two-way-anova-python/

# Group = Direct or Anon
# Type = Neutral or Inflam

# Example
# model = ols('height ~ C(water) + C(sun) + C(water):C(sun)', data=df).fit()

In [3]:
columns = ['Comfort', 'Stress', 'Openness', 'Speech_concern', 'Perception_concern', 'Divulgence']

df[columns].corr()

,Comfort,Stress,Openness,Speech_concern,Perception_concern,Divulgence
Comfort,1.000000,-0.432025,0.413743,-0.350368,-0.522649,0.322299
Stress,-0.432025,1.000000,0.201640,0.439555,0.652922,0.288815
Openness,0.413743,0.201640,1.000000,0.127959,0.076790,0.933817
Speech_concern,-0.350368,0.439555,0.127959,1.000000,0.726190,0.321960
Perception_concern,-0.522649,0.652922,0.076790,0.726190,1.000000,0.185095
Divulgence,0.322299,0.288815,0.933817,0.321960,0.185095,1.000000

In [4]:
# Impact of Type and group on stress perception

model = ols("Stress ~ C(Group) + C(Type) + C(Group):C(Type)", data=df).fit()
sm.stats.anova_lm(model, typ=2)

                     sum_sq   df         F    PR(>F)
C(Group)          10.083333  1.0  1.592105  0.242570
C(Type)            0.083333  1.0  0.013158  0.911503
C(Group):C(Type)   0.083333  1.0  0.013158  0.911503
Residual          50.666667  8.0       NaN       NaN

In [5]:
# Impact of Type and group on the participants concern over what they said

model = ols("Perception_concern ~ C(Group) + C(Type) + C(Group):C(Type)", data=df).fit()
sm.stats.anova_lm(model, typ=2)

                     sum_sq   df         F    PR(>F)
C(Group)          21.333333  1.0  2.909091  0.126475
C(Type)            5.333333  1.0  0.727273  0.418567
C(Group):C(Type)   0.333333  1.0  0.045455  0.836503
Residual          58.666667  8.0       NaN       NaN

In [6]:
# Impact of Type and group on the participants concern over how their comments were percieved

model = ols("Speech_concern ~ C(Group) + C(Type) + C(Group):C(Type)", data=df).fit()
sm.stats.anova_lm(model, typ=2)

                        sum_sq   df             F    PR(>F)
C(Group)          3.333333e-01  1.0  5.405405e-02  0.821991
C(Type)           1.333333e+00  1.0  2.162162e-01  0.654333
C(Group):C(Type)  5.916457e-31  1.0  9.594254e-32  1.000000
Residual          4.933333e+01  8.0           NaN       NaN

In [7]:
# Impact of Type and group on the participants perception of the openness of the conversation

model = ols("Openness ~ C(Group) + C(Type) + C(Group):C(Type)", data=df).fit()
sm.stats.anova_lm(model, typ=2)

                     sum_sq   df         F    PR(>F)
C(Group)           6.750000  1.0  3.115385  0.115555
C(Type)            0.083333  1.0  0.038462  0.849409
C(Group):C(Type)   0.083333  1.0  0.038462  0.849409
Residual          17.333333  8.0       NaN       NaN

In [8]:
# Impact of Type and group on the participants perception of the comfort of the conversation

model = ols("Comfort ~ C(Group) + C(Type) + C(Group):C(Type)", data=df).fit()
sm.stats.anova_lm(model, typ=2)

                     sum_sq   df         F    PR(>F)
C(Group)           2.083333  1.0  0.390625  0.549378
C(Type)            2.083333  1.0  0.390625  0.549378
C(Group):C(Type)   2.083333  1.0  0.390625  0.549378
Residual          42.666667  8.0       NaN       NaN

In [9]:
# Impact of Type and group on the participants willingness to divulge information
model = ols("Divulgence ~ C(Group) + C(Type) + C(Group):C(Type)", data=df).fit()
sm.stats.anova_lm(model, typ=2)

                     sum_sq   df         F    PR(>F)
C(Group)          12.000000  1.0  2.285714  0.169020
C(Type)            0.333333  1.0  0.063492  0.807412
C(Group):C(Type)   0.333333  1.0  0.063492  0.807412
Residual          42.000000  8.0       NaN       NaN